# Generated by Django 3.0.3 on 2020-02-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(default=1, upload_to='books'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
