# Generated by Django 3.0.3 on 2020-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0003_auto_20200215_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
