# Generated by Django 3.0.3 on 2020-02-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0005_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
