# Generated by Django 3.0.3 on 2020-02-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0007_auto_20200216_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, to='ereader.Category'),
        ),
    ]
