# Generated by Django 3.0.3 on 2020-02-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0008_auto_20200216_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(upload_to='static/books'),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
